import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { StoreProvider } from "@/providers/StoreProvider";
import { AppThemeProvider } from "@/providers/AppThemeProvider";
import { Header } from "@/components/landing/Header/Header";
import { Footer } from "@/components/landing/Footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased scroll-smooth`}
    >
      <body className="min-h-full flex flex-col bg-canvas font-sans selection:bg-brand/20 selection:text-brand antialiased">
        <StoreProvider>
          <AppThemeProvider>
            <Header />
            <main className="flex-1 w-full">
              {children}
            </main>
            <Footer />
          </AppThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
