server {
    listen 80;
    server_name lugh.site www.lugh.site;
    # הפנייה אוטומטית ל-HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name lugh.site www.lugh.site;

    # Certbot כבר יצר את הקבצים האלו בשרת, אנחנו רק מפנים אליהם
    ssl_certificate /etc/letsencrypt/live/lugh.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lugh.site/privkey.pem;

    # אופטימיזציה ל-SSL (אופציונלי אבל מומלץ)
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        proxy_pass http://localhost:3000; # הפורט של קונטיינר ה-Frontend
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}