server {
    listen 80;
    server_name lugh.site www.lugh.site;
    return 301 https://$host$request_uri; # הפניה אוטומטית ל-HTTPS
}

server {
    listen 443 ssl;
    server_name lugh.site www.lugh.site;

    # נתיבים קבועים לתעודות שכבר קיימות בשרת
    ssl_certificate /etc/letsencrypt/live/lugh.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lugh.site/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }
}